### ISSUE TITLE
Undefined property: FTPServer\User::$status

### ISSUE THREAD

**Issue by winternet-studio** [zhusaidong/FTPServer#2]
When trying to login with my FTP client I get this error on the server:

`Notice: Undefined property: FTPServer\User::$status in /data/programs/ftp-server/vendor/zhusaidong/ftp-server/src/FTPCommand.php on line 237`

It's trying to access a `status` property but that doesn't exist in `user.json`... I can't even figure out where that property is used?

**Comment by zhusaidong** [comment]
sorry, my fault. you can add `status` in user.json like:
```
{
	"test": {
		"username": "test",
		"password": "123",
		"path": "/",
		"status": true
	}
}
```

**Comment by winternet-studio** [comment]
Ok, so it's basically a flag enabling or disabling the user. Thanks!
